---
apiVersion: v1
kind: Namespace
metadata:
  name: simkube
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sk-tracer-configmap-c860a579
  namespace: simkube
data:
  tracer-config.yml: |
    ---
    trackedObjects:
      kubecon.appliedcomputing.io/v1.ConJob:
        podSpecTemplatePath: /spec/template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-tracer-service-account-c8f41577
  namespace: simkube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sk-tracer-cluster-role-binding-c8b0436a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sk-tracer-service-account-c8f41577
    namespace: simkube
---
apiVersion: v1
kind: Service
metadata:
  name: sk-tracer-service-c8512652
  namespace: simkube
spec:
  ports:
    - port: 7777
      targetPort: 7777
  selector:
    app: sk-tracer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sk-tracer
  name: sk-tracer-deployment-c8ae44bd
  namespace: simkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-tracer
  template:
    metadata:
      labels:
        app: sk-tracer
      namespace: simkube
    spec:
      containers:
        - args:
            - /sk-tracer
            - --server-port
            - "7777"
            - -c
            - /config/tracer-config.yml
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: POD_OWNER
              value: sk-tracer-deployment-c8ae44bd
          image: localhost:5000/sk-tracer:770c3e2-b68ea00e9c666b272e6c3fc53a8ff0fb76f414d0
          name: sk-tracer
          ports:
            - containerPort: 7777
          volumeMounts:
            - mountPath: /config
              name: tracer-config
      nodeSelector:
        type: kind-worker
      serviceAccountName: sk-tracer-service-account-c8f41577
      volumes:
        - configMap:
            items:
              - key: tracer-config.yml
                path: tracer-config.yml
            name: sk-tracer-configmap-c860a579
          name: tracer-config
