{
 "title": "Production Data",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pod Counts",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"conjobs\", phase=~\"(Running|Pending)\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulated Pod Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"conjobs\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Node Count",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "Node Count"
    }
   ]
  }
 ]
}