package main

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"sync"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	kubeconv1 "github.com/acrlabs/kubecon-na2023/controller/api/v1"
)

const suffixLen = 5

//nolint:gochecknoglobals
var (
	conjobScheme = runtime.NewScheme()
	setupLog     = ctrl.Log.WithName("setup")
	letters      = []rune("abcdefghijklmnopqrstuvwxyz0123456789")
)

// ConJobReconciler reconciles a ConJob object
type ConJobReconciler struct {
	client  client.Client
	scheme  *runtime.Scheme
	running sync.Mutex
}

//+kubebuilder:rbac:groups=core,resources=pods,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=core,resources=pods/status,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=kubecon.appliedcomputing.io,resources=conjobs,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=kubecon.appliedcomputing.io,resources=conjobs/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=kubecon.appliedcomputing.io,resources=conjobs/finalizers,verbs=update

func buildPod(conJob *kubeconv1.ConJob, scheme *runtime.Scheme) (*corev1.Pod, error) {
	suffix := make([]rune, suffixLen)
	for i := range suffix {
		suffix[i] = letters[rand.Intn(len(letters))]
	}

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Namespace:   conJob.ObjectMeta.Namespace,
			Name:        fmt.Sprintf("%s-%s", conJob.ObjectMeta.Name, string(suffix)),
			Annotations: make(map[string]string),
			Labels:      make(map[string]string),
		},
		Spec: *conJob.Spec.Template.Spec.DeepCopy(),
	}
	for k, v := range conJob.Spec.Template.Annotations {
		pod.Annotations[k] = v
	}
	for k, v := range conJob.Spec.Template.Labels {
		pod.Labels[k] = v
	}
	if err := ctrl.SetControllerReference(conJob, pod, scheme); err != nil {
		return nil, err
	}

	return pod, nil
}

func (self *ConJobReconciler) doWork(ctx context.Context, namespacedName types.NamespacedName) {
	defer self.running.Unlock()

	logger := log.FromContext(ctx)
	for {
		var conJob kubeconv1.ConJob
		if err := self.client.Get(ctx, namespacedName, &conJob); err != nil {
			logger.Error(err, "could not get ConJob", "name", namespacedName)
			break
		}

		go func() {
			logger.Info("creating pod objects")

			for i := int32(0); i < conJob.Spec.Pods; i++ {
				pod, err := buildPod(&conJob, self.scheme)
				if err != nil {
					logger.Error(err, "could not build pod object")
				}

				if err := self.client.Create(context.Background(), pod); err != nil {
					logger.Error(err, "could not create pod")
				}
			}
		}()

		logger.Info("sleeping", "delay", conJob.Spec.Delay)
		time.Sleep(time.Duration(conJob.Spec.Delay) * time.Second)
	}
}

func (self *ConJobReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)
	logger.Info("got new request", "request", req)

	self.running.Lock()

	go self.doWork(ctx, req.NamespacedName)

	return ctrl.Result{}, nil
}

func (self *ConJobReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&kubeconv1.ConJob{}).
		Complete(self)
}

func main() {
	opts := zap.Options{
		Development: true,
	}

	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme: conjobScheme,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	if err = (&ConJobReconciler{
		client: mgr.GetClient(),
		scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "ConJob")
		os.Exit(1)
	}

	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}

//nolint:gochecknoinits // generated by kubebuilder
func init() {
	utilruntime.Must(scheme.AddToScheme(conjobScheme))
	utilruntime.Must(kubeconv1.AddToScheme(conjobScheme))
}
