---
apiVersion: v1
kind: Namespace
metadata:
  name: conjob-ctrl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjob-manager-sa
  namespace: conjob-ctrl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sk-vnode-cluster-role-binding-c8d91260
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjob-manager-role
subjects:
  - kind: ServiceAccount
    name: conjob-manager-sa
    namespace: conjob-ctrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conjob-ctrl
  name: conjob-ctrl
  namespace: conjob-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjob-ctrl
  template:
    metadata:
      labels:
        app: conjob-ctrl
      namespace: conjob-ctrl
    spec:
      containers:
        - args:
            - /conjob-ctrl
          image: localhost:5000/conjob-controller:latest
          imagePullPolicy: Always
          name: ctrl
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      nodeSelector:
        kubernetes.io/hostname: production-worker
      serviceAccountName: conjob-manager-sa
